---
title: "Pesquisa de Satisfação do Estágio"
author: "Prof. MSc. Edgar Luiz de Lima"
date: "13/07/2022"
output: html_document
---

# 1. Preparação do ambiente e dos dados

1.1 Carregando os pacotes.
```{r}
library(openxlsx)
library(ggplot2)
library(dplyr)
library(ggpubr)
```

1.2 Carregando o conjunto de dados.
```{r}
dados<- read.xlsx("satisfacao.xlsx")
View(dados)
```
1.3 Retirando as colunas com NA.
```{r}
teste<- is.na(dados)
teste2<- colSums(teste)
dados2<- dados[,which(teste2==0)]
dados3<- dados2[, - c(1:4)]
View(dados3)
ncol(dados3)
```

1.4 Montando as colunas de contagem.
```{r}
frequencia<- matrix(0,5,8)

frequencia[c(3,4,5),1]<- as.data.frame(table(dados3[,1]))[,2]
frequencia[c(3,4,5),2]<- as.data.frame(table(dados3[,2]))[,2]
frequencia[c(1:5),3]<- as.data.frame(table(dados3[,3]))[,2]
frequencia[c(2:5),4]<- as.data.frame(table(dados3[,4]))[,2]
frequencia[c(1,3,4,5),5]<- as.data.frame(table(dados3[,5]))[,2]
frequencia[c(3,4,5),6]<- as.data.frame(table(dados3[,6]))[,2]
frequencia[c(1:5),7]<- as.data.frame(table(dados3[,7]))[,2]
frequencia[c(1,3,4,5),8]<- as.data.frame(table(dados3[,8]))[,2]


```

1.5 Calculando a percentagem de respostas
```{r}
# Vetor com as classes
Conceito<- c("Disc. Totalmente", "Discordo", 
             "Neutro", "Concordo","Conc. Totalmente")

percent<-(frequencia/colSums(frequencia))*100

resp<- data.frame(Conceito, percent)
names(resp)<- c("Conceito","Q1","Q2","Q3","Q4","Q5","Q6","Q7","Q8")
View(resp)
```

# Construindo as figuras